const subjectsTypes = {
    GET_ALL_SUBJECTS_SUCCESS: 'GET_ALL_SUBJECTS_SUCCESS',
    GET_ALL_SUBJECTS_LOADING: 'GET_ALL_SUBJECTS_LOADING',
    GET_ALL_SUBJECTS_ERROR: 'GET_ALL_SUBJECTS_ERROR',
    GET_FILTERED_SUBJECTS_SUCCESS: 'GET_FILTERED_SUBJECTS_SUCCESS',
    GET_FILTERED_SUBJECTS_LOADING: 'GET_FILTERED_SUBJECTS_LOADING',
    GET_FILTERED_SUBJECTS_ERROR: 'GET_FILTERED_SUBJECTS_ERROR',
    GET_SUBJECTS_SUCCESS: 'GET_SUBJECTS_SUCCESS',
    GET_SUBJECTS_ERROR: 'GET_SUBJECTS_ERROR',
    GET_FILTERED_COURSES_SUCCESS:'GET_FILTERED_COURSES_SUCCESS',
    GET_FILTERED_COURSES_LOADING:'GET_FILTERED_COURSES_LOADING',
    GET_FILTERED_COURSES_ERROR:'GET_FILTERED_COURSES_ERROR'
};
export default subjectsTypes;